### ISSUE TITLE
Code Check

### ISSUE THREAD

**Issue by tkt8** [tkt8/LightItUp#26]
Can you please help me with the code? On line 37 the flow is passing through the if even when the button is not pressed and the operating mode keeps toggling continuously.  I cannot figure out why.

**Comment by mlp6** [comment]
https://github.com/tkt8/LightItUp/blob/e71b848ee7b74ecb982f92ca1bb226b044b7be50/Software/led_blink/led_blink.ino#L37

**Comment by mlp6** [comment]
Have you output the state of `buttonIsPushed` when it is being evaluated at this line?  Is it actually `true`?

**Comment by tkt8** [comment]
It keeps toggling. Have tried changing the button also to no avail

**Comment by mlp6** [comment]
I would avoid using the `delay()` command if possible.  That will stall the running `loop()`, which can make the operation of the device "clunky".  Do you need all of those 1 sec delays?

**Comment by tkt8** [comment]
That was just to visualize the serial monitor status. Will remove them just in case and try.

**Comment by tkt8** [comment]
Found out the reason it was toggling. Code is working now. Thanks
